#端口
server:
  port: 8080
  servlet:
    context-path: /asong


#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/META-INF/mapper/**/*Mapper.xml
  typeAliasesPackage: org.lvjiang.song.asong.entity
  global-config:
    id-type: 0 #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    db-column-underline: true #驼峰下划线转换
    refresh-mapper: true #刷新mapper 调试神器
    capital-mode: true #数据库大写下划线转换
  configuration:
    map-underscore-to-camel-case: true #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    cache-enabled: false

spring:
  application:
    name: song-asong
  datasource:
    url: jdbc:mysql://evan.c3o6e82cgeo9.ap-northeast-1.rds.amazonaws.com:3306/test?useSSL=false&serverTimezone=UTC
    username: root
    password: wfaxx19950129
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      # Nacos服务地址
      server-addr: localhost:8848
      # Nacos的服务注册与发现
      discovery:
        # Nacos服务地址
        #server-addr: localhost:8848
        # 配置集群名称，也就是机房位置，例如：HZ 杭州
        cluster-name: HZ
        # Nacos可视化命名空间ID
    # namespace:


apollo:
  bootstrap:
    enabled: true

management:
  endpoint:
    health:
      group:
        readinessState:
          exclude: elasticsearchRest,sentinel,db
        livenessState:
          exclude: elasticsearchRest,sentinel,db